export const GET_REQUEST_ADMIN_SIDE = "GET_REQUEST_ADMIN_SIDE";
export const GET_REQUEST_SUCCESS_ADMIN_SIDE = "GET_REQUEST_SUCCESS_ADMIN_SIDE";
export const GET_REQUEST_FAILURE_ADMIN_SIDE = "GET_REQUEST_FAILURE_ADMIN_SIDE";

export const PATCH_REQUEST_ADMIN_SIDE = "GET_REQUEST_ADMIN_SIDE";
export const PATCH_REQUEST_SUCCESS_ADMIN_SIDE =
  "GET_REQUEST_SUCCESS_ADMIN_SIDE";
export const PATCH_REQUEST_FAILURE_ADMIN_SIDE =
  "GET_REQUEST_FAILURE_ADMIN_SIDE";

export const GET_REQUEST_CART = "GET_REQUEST_CART";
export const GET_REQUEST_SUCCESS_CART = "GET_REQUEST_SUCCESS_CART";
export const GET_REQUEST_FAILURE_CART = "GET_REQUEST_FAILURE_CART";

export const GET_REQUEST_USER = "GET_REQUEST_USER";
export const GET_REQUEST_SUCCESS_USER = "GET_REQUEST_SUCCESS_USER";
export const GET_REQUEST_FAILURE_USER = "GET_REQUEST_FAILURE_USER";

export const DELETE_USER_DATA = "DELETE_USER_DATA";
